namespace Employee
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");

            Employee employee1 = new Employee("Arpit");
           
           
        }
    }

    class Employee
    {
        private string name;

        private int empNo;

        private decimal basic;
        public decimal Basic { get; set; }
        public short deptNo;
       
        private static int autoGenerated = 0;

        public string Name
        {
            get { return name; }
            set
            {
                if (value.Length == 0) { Console.WriteLine("Name cannot be the nulll"); }
                else { name = value; }
            }
        }

        public  int EmpNo
        {
            get { return empNo; }

            set { empNo = value; }
     
        }

        public short DeptNo
        {
            set 
            {    
                if(value < 0)
                    Console.WriteLine("DeptNo cannot be <0 ");
                else { deptNo = value; }
            }
            get { return deptNo; }
        }


        public Employee(String name = "", decimal basic = 0, short deptNo = 0)
        {
            this.Name = name;
            this.Basic = basic;
            this.DeptNo = deptNo;
            this.EmpNo = ++autoGenerated;
        }

        public decimal GetNetSalary()
        {
            return Basic + 2000;
        }

    }
}
